Rpm Stats Automated Tests
tidepool-org/WebUITests pull request #35
Opened 2024-06-25 03:38 UTC by brian-tidepool

Added tests for PRD and QA2 that filter the clinic patient list, export the RPM stats report, and checks the validity of the data sufficiency column. Automated tests that were implemented were marked in the test strategy spreadsheet:

https://docs.google.com/spreadsheets/d/1gv5q_o5ghR_KMENYvsFmFxGVjKz020O9/edit?usp=sharing&ouid=117042773141856291352&rtpof=true&sd=true

2024-07-12 13:03 UTC, vojtech-cerveny commented
It is kinda hard to read, when this PR contains previous PRs. Should I comment here everything what I commented there or should I compare these 3 PRs? :) 

I would suggest - do a sequential merging - First one is the base, second PR should be into the base (previous) and third PR should be into the second PR (previous). 

* We can see really only changes for that PR (not previous changes)
* You need merge it in sequence. 

Or this should be without previous PRs (so you started from main, not the [clinicianlogin](https://github.com/tidepool-org/WebUITests/tree/clinicianlogin)).

2024-07-12 20:40 UTC, brian-tidepool commented
> It is kinda hard to read, when this PR contains previous PRs. Should I comment here everything what I commented there or should I compare these 3 PRs? :)
> 
> I would suggest - do a sequential merging - First one is the base, second PR should be into the base (previous) and third PR should be into the second PR (previous).
> 
> * We can see really only changes for that PR (not previous changes)
> * You need merge it in sequence.
> 
> Or this should be without previous PRs (so you started from main, not the [clinicianlogin](https://github.com/tidepool-org/WebUITests/tree/clinicianlogin)).

The PR depends on the previous PRs. I'll see if i can create a branch that commits on top of merged changes.

2024-07-12 21:03 UTC, brian-tidepool commented
@vojtech-cerveny i changed the base branch of the pull request to clinicianlogin. does this separate out the new changes?

2024-07-12 21:12 UTC, brian-tidepool reviewed
suppressed notification branch

2024-07-12 21:32 UTC, brian-tidepool commented
@vojtech-cerveny i squashed all the new changes related to this branch into one commit: https://github.com/tidepool-org/WebUITests/pull/35/commits/0bcb695149f4f07b6945e39d9d2cf0dec790799f

 let me know if this fixes the readability issue

2024-07-13 10:00 UTC, vojtech-cerveny commented
@brian-tidepool - I think that you should have [supressednotificationstest](https://github.com/tidepool-org/WebUITests/tree/supressednotificationstest) as base branch - check this, I tried to change it and it seems that this PR really contains only RPM changes.

Wdyt?

2024-07-15 15:39 UTC, vojtech-cerveny requested changes
This needs some extra work. 
Please check also eslint. It throws a lot of errors. 

```
npx eslint . --fix //this automatically fix small issues
npx eslint .

✖ 172 problems (150 errors, 22 warnings)
```

Let me know if you have any questions or I can help you with something.

2024-07-15 17:12 UTC, brian-tidepool commented
> @brian-tidepool - I think that you should have [supressednotificationstest](https://github.com/tidepool-org/WebUITests/tree/supressednotificationstest) as base branch - check this, I tried to change it and it seems that this PR really contains only RPM changes.
> 
> Wdyt?

sounds good like a good change, can try this

2024-07-18 18:28 UTC, brian-tidepool commented
> This needs some extra work. Please check also eslint. It throws a lot of errors.
> 
> ```
> npx eslint . --fix //this automatically fix small issues
> npx eslint .
> 
> ✖ 172 problems (150 errors, 22 warnings)
> ```
> 
> Let me know if you have any questions or I can help you with something.

all eslint errors fixed except class-methods-use-this which causes an error

see commit:

https://github.com/tidepool-org/WebUITests/commit/2d90b574128c0365533e4bb77da0ed26ad01a532

2024-08-02 22:08 UTC, brian-tidepool commented on .circleci/config.yml
> +      default: "testqa2ChromeRpm"
reverted to testParallel in commit 5002a5489456970f55bbafa3e5e0f46253a10291

2024-08-02 22:21 UTC, brian-tidepool commented on custom_commands/checkFileContents.js
> +   * @
added documentation fileName in commit 7f8d61fe1d3dbc323fccca51dc6b76e8d784338b

2024-08-02 22:55 UTC, brian-tidepool commented on custom_commands/checkRPMExportSufficiency.js
> +function checkSufficiency(item) {
added documentation to function in commit bae15b7acf16422b647781bd02916db5c99bb598

2024-08-05 18:33 UTC, brian-tidepool commented on pageobjects/clinicPatientListPage.js
> +        rpmReportButton: {
deferring the conversion from xpath to css for later time

2024-08-05 23:53 UTC, brian-tidepool commented on tests/e2e/rpmStatsFunctionalityLastUploadFilterAllRanges.js
> +    const attemptsCheckFileExists = 10;
date string creation moved to function createDatesLong and createDateShort in commit 322895bcf7a7f35db7ba1f39879a3619edda6863

2024-08-06 00:06 UTC, brian-tidepool commented on pageobjects/clinicPatientListPage.js
> +
steps removed in commit 0f4324d4bc59e927e3a0667ad94ac2f7ee5a42f4

2024-08-06 00:08 UTC, brian-tidepool commented on tests/e2e/rpmStatsFunctionalityLastUploadFilterToday.js
> +    const sufficient = await browser.checkRPMExportSufficiency(filePath);
filePath is the correct variable

2024-08-06 01:32 UTC, merged